### ISSUE TITLE
automatically check Debian package for problems

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1246]
run `lintian` in the workflow that builds the Debian package to check it for problems

https://lintian.debian.org/manual/index.html

```yaml
# nfpm.yaml to add lintian overrides in the built deb
contents:
- src: .lintian-overrides
  dst: ./usr/share/lintian/overrides/nfpm
  packager: deb
  file_info:
    mode: 0644
```
