### ISSUE TITLE
delay downstream releases until pre-release promoted to latest

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1957]
We're releasing the Linux packages and container images when the GitHub release is published, but not filtering for pre-releases vs. "latest" releases, which is a feature of GH Releases API.

Delay releasing those downstream artifacts, which can not be clawed back, until the GitHub release is flagged "latest."

This adopts a similar pattern as used by ZET to ensure a greater burn-in for the downstreams, and sets a more conservative expectation for GitHub pre-releases.

**Comment by qrkourier** [comment]
This will involve a combination of event-specific and activity-specific workflow triggers like this:

```yaml
  release:
    types:
      - released  # excludes "prereleased" which is included in "published" to
                  # avoid prematurely releasing semver tagged container images
```

and new conditional expressions within the main.yml workflow that's currently calling the workflows where the images and packages are built and published.

The pattern I used for ZET was to publish releases to a test repo, then later promote the artifact to the main repo when the GitHub release is promoted to latest.
