### ISSUE TITLE
release ci - publish container image attestations 

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#2011]
The container images must be hardened, scanned, and signed to satisfy security minimums for production deployments (e.g., Docker, Kubernetes).

The popular approach to hardening seems to be switching to a source image that is comparatively free of CVEs, and that seems like the only sensible approach. 

Our current images are sourcing the RedHat Universal Base Image (UBI) minimal variant, which reportedly has about 2/3 as many CVEs as a comparable Debian image, so we're not in the worst possible condition. Using the UBI is a prerequisite for OpenShift certification. So, if we decide to pursue that certification and have switched away from the UBI, we'd have to create a parallel UBI-based image build or switch back to the UBI.

Alternative images billed as "hardened" include ChainGuard's, USAF's Iron Bank, and Canonical's Chiselled.

Resources:

- https://www.chainguard.dev/
- https://docs.sigstore.dev/signing/signing_with_containers/
- https://github.com/openpubkey/openpubkey?tab=readme-ov-file#readme
- https://notaryproject.dev/
- https://docs.docker.com/engine/security/trust/

**Comment by qrkourier** [comment]
GitHub attestations use industry-standard SLSA attestations for arbitrary artifacts, including SBOM, binary, container image, allowing consumers to verify the artifact was built by a particular GitHub identity and workflow on a specific GitHub release tag.

Here's a CLI example for querying for attestations that may exist for a specific container image by owner/repo:tag@hash. The attestation exists in the OCI registry and GitHub's attestations API.

This example answers the question, "Hey, GitHub, does this amd64/x86_64 container image with the `0.2.0-alpha7` tag represent a verifiable build from the `v0.2.0-alpha7` Git tag in the `qrkourier/ziti-k8s-agent` GitHub repo?`

```bash
❯ gh attestation verify --owner qrkourier oci://docker.io/kbinghamnetfoundry/ziti-k8s-agent:0.2.0-alpha7@sha256:d95806361a0c02ee41029447baae6d43f0fa67198e406c94296e436a71907ed4
Loaded digest sha256:d95806361a0c02ee41029447baae6d43f0fa67198e406c94296e436a71907ed4 for oci://docker.io/kbinghamnetfoundry/ziti-k8s-agent:0.2.0-alpha7@sha256:d95806361a0c02ee41029447baae6d43f0fa67198e406c94296e436a71907ed4
Loaded 1 attestation from GitHub API

The following policy criteria will be enforced:
- Predicate type must match:................ https://slsa.dev/provenance/v1
- Source Repository Owner URI must match:... https://github.com/qrkourier
- Subject Alternative Name must match regex: (?i)^https://github.com/qrkourier/
- OIDC Issuer must match:................... https://token.actions.githubusercontent.com

✓ Verification succeeded!

The following 1 attestation matched the policy criteria

- Attestation #1
  - Build repo:..... qrkourier/ziti-k8s-agent
  - Build workflow:. .github/workflows/pre-release.yml@refs/tags/v0.2.0-alpha7
  - Signer repo:.... qrkourier/ziti-k8s-agent
  - Signer workflow: .github/workflows/pre-release.yml@refs/tags/v0.2.0-alpha7
```

This approach bundles SLSA attestations (with in-toto predicate statements), adhering to the Cosign bundle spec in OCI registries, and appears robust and well-suited for arbitrary artifacts, including SBOMs, binaries, container images, etc.

Here's a GitHub Actions snippet that accomplishes this for a container image. There's another input shape for the same action for file artifacts like SBOM, binary, etc. that uses a path and works in conjunction with the upload-artifact Action to pass the file integrity hash.

```yaml
jobs:
  pre-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # need write to create release
      id-token: write  # need write to get OIDC token for generating attestations
      attestations: write  # need write to create attestations

# ...

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY}}/${{ env.IMAGE_REPO}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

```

**Overview** - GitHub attestations doc: https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds

**Specific** - Action doc: https://github.com/actions/attest-build-provenance?tab=readme-ov-file#container-image
