### ISSUE TITLE
Docker ziti-router: Bootstrap fabric router, wrong commands

### ISSUE THREAD

**Issue by tekook** [openziti/ziti#2163]
Hi erveryone,
using the ziti-router docker image the bootstrap of a fabric router is not possible.
The creation of the config uses a wrong command line resulting in error:
`Error: unknown flag: --tunnelerMode`

My current compose is as follows:
[docker-compose.txt](https://github.com/user-attachments/files/15976039/docker-compose.txt)
Basically setting "ZITI_ROUTER_TYPE" to "fabric" kills the bootstrap, because the bootstrap uses the flag "--tunnlerMode"

I guess it's because of line 19 in [bootstrap.bash](https://github.com/openziti/ziti/blob/release-next/dist/dist-packages/linux/openziti-router/bootstrap.bash) which always adds the flag.

Kind Regards

**Comment by qrkourier** [comment]
Thanks for the report! The associated branch fixes the bug generates a config like this when `ZITI_ROUTER_TYPE=fabric`.

You can test it out early if you wish with image `docker.io/kbinghamnetfoundry/ziti-router:0.0.0-9dc574fde`.

```yaml
v: 3

identity:
  cert:             "/ziti-router/router.cert"
  server_cert:      "/ziti-router/router.server.chain.cert"
  key:              "/ziti-router/router.key"
  ca:               "/ziti-router/router.cas"
  #alt_server_certs:
  #  - server_cert:  ""
  #    server_key:   ""

ctrl:
  endpoint:             tls:localhost:1280

link:
  dialers:
    - binding: transport
  listeners:
    - binding:          transport
      bind:             tls:0.0.0.0:3022
      advertise:        tls:localhost:3022
      options:
        outQueueSize:   4

#listeners:
# bindings of edge and tunnel requires an "edge" section below
#  - binding: edge
#    address: tls:0.0.0.0:3022
#    options:
#      advertise: localhost:3022
#      connectTimeoutMs: 5000
#      getSessionTimeout: 60
#  - binding: tunnel
#    options:
#      mode: host #tproxy|host

csr:
  country: US
  province: NC
  locality: Charlotte
  organization: NetFoundry
  organizationalUnit: Ziti
  sans:
    dns:
      - localhost
      - localhost
      - mira
    ip:
      - "127.0.0.1"


#transport:
#  ws:
#    writeTimeout: 10
#    readTimeout: 5
#    idleTimeout: 120
#    pongTimeout: 60
#    pingInterval: 54
#    handshakeTimeout: 10
#    readBufferSize: 4096
#    writeBufferSize: 4096
#    enableCompression: true
#    server_cert: /ziti-router/router.server.chain.cert
#    key: /ziti-router/router.key
#alt_server_certs:
#  - server_cert:  ""
#    server_key:   ""
forwarder:
  latencyProbeInterval: 0
  xgressDialQueueLength: 1000
  xgressDialWorkerCount: 128
  linkDialQueueLength: 1000
  linkDialWorkerCount: 32

```
