### ISSUE TITLE
handle env vars in zac binding

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#2166]
This doesn't work for some reason, but env vars work in most (all?) places in the controller config.yml.

```yaml
      - binding: zac
        options:
          location: ${ZITI_HOME}/zac
          indexFile: index.html
```
