### ISSUE TITLE
Enabling any health check causes WARNING to be logged

### ISSUE THREAD

**Issue by emoscardini** [openziti/ziti#2424]
Adding the healthChecks key with at least one health check to the ER configuration always produces:
```
WARNING ziti/router.LoadConfig: invalid [healthChecks] stanza
```

Using the example from https://github.com/openziti/ziti/blob/main/etc/edge.router.yml

```
healthChecks:
  ctrlPingCheck:
    # How often to ping the controller over the control channel. Defaults to 30 seconds
    interval: 30s
    # When to timeout the ping. Defaults to 15 seconds
    timeout: 15s
    # How long to wait before pinging the controller. Defaults to 15 seconds
    initialDelay: 15s
  linkCheck:
    # Number of links required for the health check to be passing. Defaults to 0
    minLinks: 1
    # How often to check the link count, defaults to 5s
    interval: 5s
    # How long to wait before running the first check. Defaults to 1s
    initialDelay: 5s
```

This doesn't stop the configured health checks from starting or running, just prints out the WARNING every time.
