### ISSUE TITLE
zrok Ingress Controller for k8s

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#2425]
The zrok Ingress Controller watches for `Ingress` and `Gateway` resources and provisions the appropriate resources in Kube API and a reserved zrok share.

Defines an `IngressClass` and `GatewayClass` named `zrok` that may be instantiated by the zrok Ingress Controller.

**example Ingress resource using the zrok class represents what the k8s user must provide to trigger the zrok Ingress Controller to proxy to a ClusterIP service**

_backend mode "proxy" is implied_

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-frontdoor-svc-ingress
  annotations:
    zrok.ingress.kubernetes.io/unique-name: myfrontdoorsvc
spec:
  ingressClassName: zrok
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-frontdoor-svc
            port:
              number: 80
```

**variation on the above, this demonstrates using the "web" backend mode to serve static assets instead of proxy to a service**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-frontdoor-assets-ingress
  annotations:
    zrok.ingress.kubernetes.io/unique-name: myfrontdoorassets
    zrok.ingress.kubernetes.io/backend-mode: web
spec:
  ingressClassName: zrok
  defaultBackend:
    resource:
      apiGroup: k8s.example.com
      kind: StorageBucket
      name: static-assets
```
