### ISSUE TITLE
Controllers with no Edge APIs errors

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#2429]
If none of the Edge APIs are configured in a controller an error occurs.

Config:
```
    apis:
      - binding: fabric
        options: { }
      - binding: edge-management
        options: { }
```

Error:
```
[2024-09-20 20:47:12.893]   FATAL github.com/openziti/xweb/v2.(*InstanceImpl).Build: error starting xweb server for edge-management: error creating server: no default handlers found
```
