### ISSUE TITLE
/edge/client/v1/controllers endpoint returns interface port and exposed address for bindings

### ISSUE THREAD

**Issue by nenkoru** [openziti/ziti#2585]
Consider this controller config.

```yaml
...
raft:
  dataDir: ./data/ctrl1
...
edge:
  api:
    address: 127.0.0.1:443
  enrollment:
    signingCert:
      cert: ./pki/ctrlsign/certs/ctrlsign.cert
      key: ./pki/ctrlsign/keys/ctrlsign.key
    edgeIdentity:
      duration: 5m
    edgeRouter:
      duration: 5m

web:
  - name: all-apis-localhost
    bindPoints:
      - interface: 0.0.0.0:1281
        address: 127.0.0.1:443
    options:
      minTLSVersion: TLS1.2
      maxTLSVersion: TLS1.3
    apis:
      - binding: health-checks
      - binding: fabric
      - binding: edge-management
      - binding: edge-client
      - binding: controller-health
      - binding: edge-oidc
```

As you can see the address here by which the xweb component has to be access is `127.0.0.1:443` and the interface it listens on is `0.0.0.0:1281`.
However, upon requesting the `/edge/client/v1/controllers` api it returns the following.
```json
{
  "data": [
    {
      "_links": {
        "self": {
          "href": "./controllers/ctrl1"
        }
      },
      ...
      "apiAddresses": {
        "edge-client": [
          {
            "url": "https://127.0.0.1:1281/edge/client/v1",
            "version": "v1"
          }
        ]
      },
      ...
    },
  ],
  "meta": {
    "filterableFields": [
     ...
    ],
    "pagination": {
      "limit": 10,
      "offset": 0,
      "totalCount": 1
    }
  }
}
```
Here you could see that the endpoint returned for edge client api is strange. 
It took the interface's port defined and the host address from `address` field, combined it together and spit out as an endpoint to query edge api.
This behaviour is observed at current HEAD of main at https://github.com/openziti/ziti/commit/1932a6d9243491773e392046d704f23c27c59726.
