### ISSUE TITLE
Split Edge APIs can cause `ziti edge login` to fail

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#2591]
*Experienced*

If the edge client and management APIs are on different bind points, the `ziti edge login` command may fail if the default API handler does not support the `**/version`  endpoint. This is likely to happen if the `zac` API bind is used.

*Expected*
`ziti edge login` continue to function.

*Reproduction*

1. Deploy a controller with the following `web` section
```
web:
  - name: client-api
    bindPoints:
      - interface: 0.0.0.0:443
        address: 127.0.0.1:443
    apis:
      - binding: edge-client
        options: {}
  - name: all-the-rest
    bindPoints:
      - interface: 0.0.0.0:8443
        address: 127.0.0.1:8443
    apis:
      - binding: edge-management
        options: { }
      - binding: fabric
        options: { }
      - binding: zac
        options:
          location: /some/path/to/ziti-console/release/package
          indexFile: index.html
```
2. Start the controller
3. Attempt to `ziti edge login 127.0.0.1:8443`
