### ISSUE TITLE
1.4.x Router - don't fail on invalid cert for heathchecks

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#2845]
With 1.4, [validation was added](https://github.com/openziti/xweb/issues/18) that causes controllers and routers to fail if the listening port is not configured with a cert valid for the advertised address. This is vital for controllers and routers normal functionality but it's not vital for healthchecks. (though it's a good idea of course)

Example:
```
web:
- name: health-check
  bindPoints:
    - interface: 0.0.0.0:8081
      address: 0.0.0.0:8081
  apis:
    - binding: health-checks
```

For now, only warn if the healthchecks are misconfigured, don't fail the router on startup.

At some point in the future healthchecks will also require a matching SANS
