### ISSUE TITLE
router healtcheck with invalid address logs error but still doesn't listen

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#2860]
```
web:
- name: health-check
  bindPoints:
    - interface: 0.0.0.0:8081
      address: 0.0.0.0:8081
  apis:
    - binding: health-checks
```

this will generate a correct warning indicating the address is incorrect, but it should be listening after. It's not
