### ISSUE TITLE
add a command-line option to check router and controller configs

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#603]
It would be helpful for automating configuration management to be able to validate the completeness and syntactic correctness of a router and controller configuration files.

```bash
$ ziti-router --check-config ./acme-router.conf
$ echo $?
0

$ ziti-controller --check-config ./acme-ctrl.conf
(stderr) ERROR: listeners must bind to discrete ports
(stderr)    ctrl.listener, mgmt.listener may not both bind to 10000/tcp
$ echo $?
255

$ ./ziti-router-check-config.sh ./acme-router.conf
$ echo $?
0
```

```bash
#!/usr/bin/env bash
# ziti-router-check-config.sh validates a ziti-router configuration file as first param

if ziti-router --check-config "$1"; then
    echo "INFO: configuration is valid"
    exit 0
else
    echo "ERROR: configuration is not valid" >&2
    exit 1
fi
```

**Comment by qrkourier** [comment]
The goal is to avoid a loss of connectivity resulting from an invalid configuration file. This idea stems from a common pattern in configuration management systems:
1. modify a configuration file to have desired directives
2. parse temp file with the CLI that will eventually load it as configuration
3. clobber the permanent file with the contents of validated temp file

It came to mind when I learned that @gberl001 is working on `ziti` CLI feature to generate valid configurations by rendering an in-built template with options and args or env vars. This made me wonder if there's a unified way of validating configs irrespective of how they were created, and @dovholuknf suggested this might best be accomplished as part of each CLI that consumes some configuration file.

```yaml
# example Ansible task from a CIS hardening role that modifies the sudoers config file only if visudo successfully validates the resultant buffer
- name: "5.2.2 | L1 | AUDIT | Ensure sudo commands use pty"
  lineinfile:
      dest: /etc/sudoers
      regexp: '^Defaults    use_pty'
      line: 'Defaults    use_pty'
      state: present
      validate: '/usr/sbin/visudo -cf %s'
```

```yaml
- name: change and validate ziti-controller config
  blockinfile:
    path: /opt/netfoundry/ziti/ziti-controller/config.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
        ctrl:
          listener:             tls:127.0.0.1:{{ziti_ctrl_fabric_port}}
        mgmt:
          listener:             tls:127.0.0.1:{{ziti_ctrl_mgmt_port}}
    validate: '/opt/netfoundry/ziti/ziti-controller/ziti-controller --check-config %s'
```
