### ISSUE TITLE
expressInstall - controller.web.port wrong

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#643]
When using expressInstall for 'host it myself' you are supposed to be able to set `export ZITI_EDGE_CONTROLLER_PORT=8441`. This works great for all the ports in the controller config file . See how address is overridden properly (:8441) but the listen interface is wrong (:1280)

```
web:
  # name - required
  # Provides a name for this listener, used for logging output. Not required to be unique, but is highly suggested.
  - name: client-management
    # bindPoints - required
    # One or more bind points are required. A bind point specifies an interface (interface:port string) that defines
    # where on the host machine the webListener will listen and the address (host:port) that should be used to
    # publicly address the webListener(i.e. mydomain.com, localhost, 127.0.0.1). This public address may be used for
    # incoming address resolution as well as used in responses in the API.
    bindPoints:
      #interface - required
      # A host:port string on which network interface to listen on. 0.0.0.0 will listen on all interfaces
      - interface: 0.0.0.0:1280
        # address - required
        # The public address that external incoming requests will be able to resolve. Used in request processing and
        # response content that requires full host:port/path addresses.
        address: bobby.com:8441
```
