### ISSUE TITLE
ZITI_EDGE_ROUTER_IP_OVERRIDE does not override the edge router advertise hostname setting only adds it to the sans->ip.

### ISSUE THREAD

**Issue by dariuszSki** [openziti/ziti#868]
One needs to use these to overcome this limitation or perhaps I am missing something. 
```
export ZITI_EDGE_ROUTER_IP_OVERRIDE="10.40.101.194"
export ZITI_EDGE_ROUTER_RAWNAME="10.40.101.194"
```
But the certs ends up looking like this:
```
edge:
  csr:
    country: US
    province: NC
    locality: Charlotte
    organization: NetFoundry
    organizationalUnit: Ziti
    sans:
      dns:
        - 10.40.101.194
        - localhost
      ip:
        - "127.0.0.1"
        - "10.40.101.194"
```
perhaps it was meant to do something like this in the template as well (not sure about the syntax though). May be wrong here in my assumption. 
```
link:
  dialers:
    - binding: transport
{{ if .Router.IsPrivate }}#{{ end }}  listeners:
{{ if .Router.IsPrivate }}#{{ end }}    - binding:          transport
{{ if .Router.IsPrivate }}#{{ end }}      bind:             tls:0.0.0.0:{{ .Router.Listener.BindPort }}
{{ if .Router.IsPrivate }}#{{ end }}      advertise:        tls:{{ if .Router.Edge.IPOverride }} {{ .Router.Edge.IPOverride }} {{else}} {{ .Router.Edge.Hostname }}:{{ .Router.Listener.BindPort }}
```
Also,  the description should probably say to "override the hostname" not "default edge router IP" if my assumptions are correct?

```ZitiEdgeRouterIPOverrideVarName                  = "ZITI_EDGE_ROUTER_IP_OVERRIDE"
ZitiEdgeRouterIPOverrideVarDescription           = "Override the default edge router IP with a custom IP, this IP will also be added to the PKI"
```
