### ISSUE TITLE
ziti create config -- unexpected identity dir

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#873]
`ziti create config controller` generates a controller config with a value of `.identity` like this:

```yaml
cert: "/kpop4.cert"
server_cert: "/kpop4.server.chain.cert"
key: "/kpop4.key"
ca: "/kpop4.ca"
```

I expected the default paths to be relative to my current working dir instead of absolute e.g.

```yaml
cert: "./kpop4.cert"
server_cert: "./kpop4.server.chain.cert"
key: "./kpop4.key"
ca: "./kpop4.ca"
```
